export const LOGIN = 'LOGIN'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const STORE_TIMESHEET = 'STORE_TIMESHEET'
export const STORE_TIMESHEET_PENDING = 'STORE_TIMESHEET_PENDING'
export const STORE_TIMESHEET_SUCCESS = 'STORE_TIMESHEET_SUCCESS'
export const STORE_TIMESHEET_ERROR = 'STORE_TIMESHEET_ERROR'


export const LOGOUT = 'LOGOUT'
export const CHANGE_ROLE = 'CHANGE_ROLE'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'